<?php
/*------------------------------------------------------------------------
 # SM Mega Menu - Version 1.1
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
global $var_yttheme;
?>

<?php if( $var_yttheme->getParam('menustyle') == 'mega' ){
		echo $this->getLayout()->createBlock('cms/block')->setBlockId('left-megamenu')->toHtml();
} else {
	echo $this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top2.phtml')->tohtml();
} ?>